services:
  xui:
    image: rahgozar94725/x-ui
    container_name: xui
    network_mode: host
    volumes:
      - "./db/:/etc/x-ui/"
      - "/opt/cert/:/opt/cert/"
    environment:
      - TZ=Asia/Tehran
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
