services:
  proxy:
    image: nginx:latest
    container_name: proxy
    network_mode: host
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - "/opt/cert/:/opt/cert/"
      - ./webroot/:/usr/share/nginx/html/
    environment:
      - TZ=Asia/Tehran
