services:
    ssr:
        image: rahgozar94725/ssr
        container_name: ssr
        network_mode: host
        restart: always
        dns:
            - 8.8.8.8
            - 8.8.4.4
        volumes:
            - ./config.json:/etc/shadowsocksr/config.json:ro
